FROM python

LABEL maintainer=jssong@somansa.com

WORKDIR /app

COPY monitor /app

COPY requirements.txt /app

RUN pip install --trusted-host pypi.org --trusted-host files.pythonhosted.org -r requirements.txt

ENTRYPOINT ["python3", "-m", "publisher"]